module.exports = {
  printWidth: 100,
  tabWidth: 4,
  useTabs: false,
  semi: false,
  singleQuote: true,
  jsxSingleQuote: true,
  bracketSpacing: true,
  htmlWhitespaceSensitivity: "css",
  embeddedLanguageFormatting: "off",
  // TODO: Convert this for standard project paths
  // importOrder: [
  //     '^(react/(.*)$)|^(react$)',
  //     '^(next/(.*)$)|^(next$)',
  //     '<THIRD_PARTY_MODULES>',
  //     '',
  //     '^types$',
  //     '^@/env(.*)$',
  //     '^@/types/(.*)$',
  //     '^@/config/(.*)$',
  //     '^@/lib/(.*)$',
  //     '^@/hooks/(.*)$',
  //     '^@shared/ui$',
  //     '^@/components/(.*)$',
  //     '^@/features/(.*)$',
  //     '^@/app/(.*)$',
  //     '',
  //     '^[./]',
  // ],
  importOrderSeparation: true,
  importOrderSortSpecifiers: true,
  importOrderBuiltinModulesToTop: true,
  importOrderParserPlugins: ["typescript", "jsx", "decorators-legacy"],
  importOrderMergeDuplicateImports: true,
  importOrderCombineTypeAndValueImports: true,
  plugins: [
    // "@ianvs/prettier-plugin-sort-imports",
    "prettier-plugin-tailwindcss",
  ],
};
