'use client'
import type { Metadata } from 'next'
import './globals.css'
import * as React from 'react'
import { Providers } from './providers'
import { fonts } from '@/app/_config/fonts'
import { Navbar } from './_components/Navbar'
import Footer from './_features/footer/Footer'
import { Box } from '@chakra-ui/react'

export default function RootLayout({ children }: { children: React.ReactNode }) {
    const { hind, montserrat } = fonts
    return (
        <html lang='en' className={`${hind.variable} ${montserrat.variable}`}>
            {/* <html lang='en'> */}
            <head>
                <title>Create next app</title>
                <meta name='description' content='Generated by create next app' />
            </head>
            <body>
                <Providers>
                    <main className='flex min-h-screen flex-col items-center justify-between'>
                        <Navbar />
                        {children}
                    </main>
                    <Footer />
                </Providers>
            </body>
        </html>
    )
}
